line-length: false
no-bare-urls: false
ul-style: false
ul-indent: false
blanks-around-fences: false
first-line-heading: false
blanks-around-lists: false
fenced-code-language: false
no-inline-html: false
blanks-around-headers: false
no-multiple-space-atx: false
no-duplicate-header: false
no-trailing-punctuation: false
header-start-left: false
single-trailing-newline: false
no-space-in-code: false
header-increment: false
ol-prefix: false
single-h1: false
ul-start-left: false
